### ISSUE TITLE
'FritzVisionSegmentationResult' has no member 'toImageMask'

### ISSUE THREAD

**Issue by netunlimited** [AlexanderKub/arkit-ml-occlusion#1]
Hey there,

Thanks for this example, however when I'm trying to build it, I get the following error:
`Value of type 'FritzVisionSegmentationResult' has no member 'toImageMask'`

Also I had to already change 
`FritzVisionPeopleSegmentationModel()`
into
`FritzVisionPeopleSegmentationModelAccurate()`

Any clue on how to fix this?

**Comment by AlexanderKub** [comment]
Hi,

Thanks for issue report. This issue related to Fritz new version API change. It takes some time for me to read change log and fix project for new version.

Also I think what accurate segmentation  variant would be too slow for realtime work with ARKit.

Anyway, this sample need some optimization for convert camera frame to Fritz image.

**Comment by AlexanderKub** [comment]
Fixed in a44826030154ad045167d1a64d72e546f4357a62
